ROLE_IDS = {
    "WWS": 1,
    "SCM": 2,
    "BODY": 3,
    "CARRIER": 4,
    "ADMIN": 5,
    "WTY": 6,
    "SCM_QUALITY": 7,
}

TIMEZONE = "America/Mexico_City"
VALID_GRADES = ["V1", "V2", "V3"]
VALID_SCM_DECISIONS = ["LOAD_WITHOUT", "WAIT", "REORGANIZE", "NEW_TRIP"]
VALID_PLANTS = ["A1", "A2"]

MIN_PASSWORD_LENGTH = 8
BCRYPT_SALT_ROUNDS = 10
VIN_LENGTH = 17

DEFAULT_PAGE_SIZE = 50
MAX_LOG_PAGE_SIZE = 200
MAX_DEFECT_CHART_ITEMS = 10
SSE_KEEPALIVE_MS = 25000
NOTIFICATION_RETENTION_HOURS = 24
NOTIFICATION_CLEANUP_INTERVAL_HOURS = 6
NOTIFICATION_KEEP_RECENT_PER_USER = 50

EXCEL_STYLES = {
    "NISSAN_RED": "FFC3142D",
    "WHITE": "FFFFFFFF",
    "BORDER_COLOR": "FFB0B0B0",
    "ROW_ALT": "FFFFF0F0",
    "ROW_NORMAL": "FFFFFFFF",
    "FONT_NAME": "Calibri",
    "APP_NAME": "Nissan Body App",
}
